# for React (create-react-app), this requires refactor:
#   - public/index.html : <script src="%PUBLIC_URL%/config/env.js"></script> 
#   - Read env vars in this format: window.process.env.REACT_APP_MY_ENVVAR , window.process.env.REACT_APP_ANOTHERENVVAR, ... etc
version: '3.9'

services:
  frontend:
    build: .
    depends_on:
      - frontend-sidecar-env-gen
    ports:
    - 8081:8080
    env_file:
    - .env
    volumes:
    - env-js:/opt/app/config:ro

  # in k8s, it will be easier using sidecar with emptyDir vol
  frontend-sidecar-env-gen:
    image: abdennour/dotenv-to-js-object:4ea
    working_dir: /data
    volumes:
    - env-js:/data
    healthcheck:
      # healthy when env.js file is not empty
      test: ["CMD", "test", "-s", "/data/env.js"]
      timeout: 1s
      start_period: 1s
      interval: 10s
      retries: 3
    command: ->
      --env-vars-filter=REACT_APP_
      --run-as=daemon
      --refresh-period=50

volumes:
  env-js:
